server:
  port: 8082
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    cache:
      channel:
        size: 25
      connection:
        mode: channel
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10