server:
  port: ${server.port:8080}

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    cache:
      channel:
        size: ${rabbitmq.cache.channel.size:25}
      connection:
        mode: ${rabbitmq.cache.connection.mode:channel}
    listener:
      simple:
        concurrency: ${rabbitmq.listener.concurrency:5}
        max-concurrency: ${rabbitmq.listener.max-concurrency:10}
  config:
    import: file:./config/application-external.yml
